# Generated by Django 4.1.2 on 2023-01-05 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_utspbo', '0009_remove_jurnal_foto_jurnal_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_daerah', models.CharField(max_length=255)),
                ('nama_wisata', models.CharField(max_length=255)),
                ('deskripsi', models.CharField(max_length=255)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Gambar')),
            ],
        ),
    ]
