# Generated by Django 4.1.2 on 2023-01-05 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_utspbo', '0010_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='coordX',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='coordY',
            field=models.FloatField(null=True),
        ),
    ]
