# Generated by Django 4.1.2 on 2023-01-05 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_utspbo', '0011_home_coordx_home_coordy'),
    ]

    operations = [
        migrations.CreateModel(
            name='koor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('coordX', models.FloatField(null=True)),
                ('coordY', models.FloatField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='home',
            name='coordX',
        ),
        migrations.RemoveField(
            model_name='home',
            name='coordY',
        ),
        migrations.AddField(
            model_name='home',
            name='coord',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_utspbo.koor'),
        ),
    ]
